### ISSUE TITLE
ModuleNotFoundError: No module named 'myapp' when run as script

### ISSUE THREAD

**Issue by Ynjxsjmh** [wimglenn/resources-example#5]
When I add funtion call to `func` in `example5.py`

```
def func():
    my_resources = importlib_resources.files("myapp") / "data_subdir"
    data = (my_resources / "binfile.dat").read_bytes()
    text = (my_resources / "textfile.txt").read_text()
    print("data: " + repr(data))
    print("text: " + text)

func()
```

and run this module as script with `python myapp/example5.py`. It says

```
C:\Users\user\Downloads\resources-example-master>python myapp\example5.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\resources-example-master\myapp\example5.py", line 18, in <module>
    func()
  File "C:\Users\user\Downloads\resources-example-master\myapp\example5.py", line 12, in func
    my_resources = importlib_resources.files("myapp") / "data_subdir"
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\importlib_resources\_common.py", line 46, in wrapper
    return func(anchor)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\importlib_resources\_common.py", line 56, in files
    return from_package(resolve(anchor))
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\importlib_resources\_common.py", line 82, in _
    return importlib.import_module(cand)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'myapp'
```

I think the problem is that there is no subfolder named `myapp` under folder `myapp`, since I'm possible to do `importlib_resources.files("data_subdir")`. I'm a bit confused with when `importlib_resources.files("myapp")` is legal.

I'm in

- Python 3.9.13
- Windows 10

**Comment by wimglenn** [comment]
This error message means that the package is not installed.  If you just cloned the repo and run as script, you don't have any package installed and hence you can't have any "package data", and that's to be expected.

Create/activate an environment and install the package, then your func() call will behave as expected.

```
python -m venv .venv
.venv\bin\python -m pip install -e .
.venv\bin\python myapp\example5.py
```
